version: 2.1

jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: .
          name: Run tests
          command: |
            dotnet test
workflows:
  default: 
    jobs:
      - build-and-test